services:
  freeradius:
    user: root
    build: ./freeradius
    ports:
      - "1812:1812/udp"
      - "1813:1813/udp"
    volumes:
      - ./freeradius/certs:/etc/freeradius/certs
      - ./freeradius/mods-config/files/authorize:/etc/freeradius/mods-config/files/authorize
      - ./freeradius/mods-enabled/eap:/etc/freeradius/eap
      - ./freeradius/mods-enabled/eap_tls:/etc/freeradius/eap_tls
    environment:
      - HOSTAPD_IP=${RADIUS_IP}
      - RADIUS_SECRET=${RADIUS_SECRET}
      - WIFI_MODE=${WIFI_MODE}

  hostapd:
    build: ./hostapd
    network_mode: host
    cap_add:
      - NET_ADMIN
    environment:
      - HOTSPOT_SSID=${HOTSPOT_SSID}
      - HOTSPOT_PASSWORD=${HOTSPOT_PASSWORD}
      - RADIUS_IP=${RADIUS_IP}
      - RADIUS_SECRET=${RADIUS_SECRET}
      - WIFI_INTERFACE=${WIFI_INTERFACE}
      - WIFI_MODE=${WIFI_MODE}
    volumes:
      - ./hostapd/hostapd.conf.template:/etc/hostapd/hostapd.conf.template
      - ./hostapd/hostapd.conf.template_WPAENT:/etc/hostapd/hostapd.conf.template_WPAENT
  dhcp:
    image: networkboot/dhcpd
    network_mode: host
    cap_add:
      - NET_ADMIN
    volumes:
      - ./dhcp:/data
    environment:
      INTERFACES: ${WIFI_INTERFACE}